# Data Source 

https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0221EN-SkillsNetwork/labs/module%206/Lab%20-%20Extract%20Transform%20Load/data/source.zip

In [36]:
import glob 
import pandas as pd 
import xml.etree.ElementTree as ET 
from datetime import datetime

In [37]:
log_file = open( "log_file.txt" )
target_file = open ("transformed_data.csv","a")

In [38]:
## CSV
def extract_from_csv(file_to_process): 
    dataframe = pd.read_csv(file_to_process) 
    return dataframe 

## JSON
def extract_from_json(file_to_process): 
    dataframe = pd.read_json(file_to_process, lines=True) 
    return dataframe 

##XML

def extract_from_xml(file_to_process): 
    dataframe = pd.DataFrame(columns=["name", "height", "weight"]) 
    tree = ET.parse(file_to_process) 
    root = tree.getroot() 
    for person in root: 
        name = person.find("name").text 
        height = float(person.find("height").text) 
        weight = float(person.find("weight").text) 
        dataframe = pd.concat([dataframe, pd.DataFrame([{"name":name, "height":height, "weight":weight}])], ignore_index=True) 
    return dataframe 

## A function to identify which function to call on basis of the filetype

def extract(): 
    extracted_data = pd.DataFrame(columns=['name','height','weight']) # create an empty data frame to hold extracted data 
     
    # process all csv files 
    """for csvfile in glob.glob('*.csv'): 
        extracted_data = pd.concat([extracted_data, pd.DataFrame(extract_from_csv(csvfile))], ignore_index=True) 
        print("csvfile: ", extracted_data)
    """        
    # process all json files 
    for jsonfile in glob.glob('*.json'): 
        extracted_data = pd.concat([extracted_data, pd.DataFrame(extract_from_json(jsonfile))], ignore_index=True)
        print("jsonfile:",extracted_data)
            
    # process all xml files 
    for xmlfile in glob.glob('*.xml'): 
        extracted_data = pd.concat([extracted_data, pd.DataFrame(extract_from_xml(xmlfile))], ignore_index=True) 
        print("xmlfile:",extracted_data)
    return extracted_data 

 #data cleaning
    
def transform(data): 
    '''Convert inches to meters and round off to two decimals 
    1 inch is 0.0254 meters '''
    data['height'] = round(data.height * 0.0254,2) 
 
    '''Convert pounds to kilograms and round off to two decimals 
    1 pound is 0.45359237 kilograms '''
    data['weight'] = round(data.weight * 0.45359237,2) 
    
    return data 

def load_data(target_file, transformed_data): 
    transformed_data.to_csv(target_file) 

def log_progress(message): 
    timestamp_format = '%Y-%h-%d-%H:%M:%S' # Year-Monthname-Day-Hour-Minute-Second 
    now = datetime.now() # get current timestamp 
    timestamp = now.strftime(timestamp_format) 
    with open("log_file.txt","a") as f: 
        f.write(timestamp + ',' + message + '\n')

In [39]:
# Log the initialization of the ETL process 
log_progress("ETL Job Started") 
 
# Log the beginning of the Extraction process 
log_progress("Extract phase Started") 
extracted_data = extract() 
 
# Log the completion of the Extraction process 
log_progress("Extract phase Ended") 
 
# Log the beginning of the Transformation process 
log_progress("Transform phase Started") 
transformed_data = transform(extracted_data) 
print("Transformed Data") 
print(transformed_data) 
 
# Log the completion of the Transformation process 
log_progress("Transform phase Ended") 
 
# Log the beginning of the Loading process 
log_progress("Load phase Started") 
load_data(target_file,transformed_data) 
 
# Log the completion of the Loading process 
log_progress("Load phase Ended") 
 
# Log the completion of the ETL process 
log_progress("ETL Job Ended")

jsonfile:     name  height  weight
0   jack   68.70  123.30
1    tom   69.80  141.49
2  tracy   70.01  136.46
3   john   67.90  112.37
jsonfile:     name  height  weight
0   jack   68.70  123.30
1    tom   69.80  141.49
2  tracy   70.01  136.46
3   john   67.90  112.37
4   jack   68.70  123.30
5    tom   69.80  141.49
6  tracy   70.01  136.46
7   john   67.90  112.37
jsonfile:      name  height  weight
0    jack   68.70  123.30
1     tom   69.80  141.49
2   tracy   70.01  136.46
3    john   67.90  112.37
4    jack   68.70  123.30
5     tom   69.80  141.49
6   tracy   70.01  136.46
7    john   67.90  112.37
8    jack   68.70  123.30
9     tom   69.80  141.49
10  tracy   70.01  136.46
11   john   67.90  112.37
xmlfile:      name  height  weight
0    jack   68.70  123.30
1     tom   69.80  141.49
2   tracy   70.01  136.46
3    john   67.90  112.37
4    jack   68.70  123.30
5     tom   69.80  141.49
6   tracy   70.01  136.46
7    john   67.90  112.37
8    jack   68.70  123.30
9     tom   69.80  141.49
10  tracy   70.01  136.46
11   john   67.90  112.37
12  simon   67.90  112.37
13  jacob   66.78  120.67
14  cindy   66.49  127.45
15   ivan   67.62  114.14
xmlfile:      name  height  weight
0    jack   68.70  123.30
1     tom   69.80  141.49
2   tracy   70.01  136.46
3    john   67.90  112.37
4    jack   68.70  123.30
5     tom   69.80  141.49
6   tracy   70.01  136.46
7    john   67.90  112.37
8    jack   68.70  123.30
9     tom   69.80  141.49
10  tracy   70.01  136.46
11   john   67.90  112.37
12  simon   67.90  112.37
13  jacob   66.78  120.67
14  cindy   66.49  127.45
15   ivan   67.62  114.14
16  simon   67.90  112.37
17  jacob   66.78  120.67
18  cindy   66.49  127.45
19   ivan   67.62  114.14
xmlfile:      name  height  weight
0    jack   68.70  123.30
1     tom   69.80  141.49
2   tracy   70.01  136.46
3    john   67.90  112.37
4    jack   68.70  123.30
5     tom   69.80  141.49
6   tracy   70.01  136.46
7    john   67.90  112.37
8    jack   68.70  123.30
9     tom   69.80  141.49
10  tracy   70.01  136.46
11   john   67.90  112.37
12  simon   67.90  112.37
13  jacob   66.78  120.67
14  cindy   66.49  127.45
15   ivan   67.62  114.14
16  simon   67.90  112.37
17  jacob   66.78  120.67
18  cindy   66.49  127.45
19   ivan   67.62  114.14
20  simon   67.90  112.37
21  jacob   66.78  120.67
22  cindy   66.49  127.45
23   ivan   67.62  114.14
Transformed Data
     name  height  weight
0    jack    1.74   55.93
1     tom    1.77   64.18
2   tracy    1.78   61.90
3    john    1.72   50.97
4    jack    1.74   55.93
5     tom    1.77   64.18
6   tracy    1.78   61.90
7    john    1.72   50.97
8    jack    1.74   55.93
9     tom    1.77   64.18
10  tracy    1.78   61.90
11   john    1.72   50.97
12  simon    1.72   50.97
13  jacob    1.70   54.73
14  cindy    1.69   57.81
15   ivan    1.72   51.77
16  simon    1.72   50.97
17  jacob    1.70   54.73
18  cindy    1.69   57.81
19   ivan    1.72   51.77
20  simon    1.72   50.97
21  jacob    1.70   54.73
22  cindy    1.69   57.81
23   ivan    1.72   51.77

In [40]:
##f=open(log_file,"r")
"""with open("log_file.txt", "r") as file:
    contents = file.read()
    print(contents)"""

'with open("log_file.txt", "r") as file:\n    contents = file.read()\n    print(contents)'